// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5Px1TPbeHL56l8_usqC7kvY1M7NCKY4Y',
    appId: '1:513229099691:web:35cbd33dcbaea872e65dee',
    messagingSenderId: '513229099691',
    projectId: 'presence-665bc',
    authDomain: 'presence-665bc.firebaseapp.com',
    storageBucket: 'presence-665bc.appspot.com',
    measurementId: 'G-585WB93SGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAskKYzLp4oufR2cSZy0eZ7h-XXSazIyNM',
    appId: '1:513229099691:android:e4ebebe87e5eff7be65dee',
    messagingSenderId: '513229099691',
    projectId: 'presence-665bc',
    storageBucket: 'presence-665bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDqPtnZ5YlA2sOkaiq5Be3qykq-9DVoBs',
    appId: '1:513229099691:ios:d085b04e15003e0ee65dee',
    messagingSenderId: '513229099691',
    projectId: 'presence-665bc',
    storageBucket: 'presence-665bc.appspot.com',
    androidClientId: '513229099691-n1t7m3t9mhhbgq8429u2itbrcn6qpsdv.apps.googleusercontent.com',
    iosClientId: '513229099691-bcdpt10a6iapderdo9rt9ss3sa8tusd7.apps.googleusercontent.com',
    iosBundleId: 'com.example.presence',
  );
}
